apiVersion: v1
kind: Service
metadata:
  name: flaky-app
  labels:
    app: flaky-app
    release: 'v{{repl KurlString "Prometheus.Version" }}'
  annotations:
    kots.io/when: '{{repl IsKurl }}'
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 3000
      name: http
  selector:
    app: flaky-app
    release: 'v{{repl KurlString "Prometheus.Version" }}'