apiVersion: v1
kind: Service
metadata:
  name: flaky-app
  labels:
    app: flaky-app
    release: 'v{{repl KurlString "Prometheus.Version" }}'
  annotations:
    kots.io/when: '{{repl (not IsKurl)}}'
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
  selector:
    app: flaky-app
    release: 'v{{repl KurlString "Prometheus.Version" }}'