apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaky-app
  labels:
    app: flaky-app
    release: 'v{{repl KurlString "Prometheus.Version" }}'
spec:
  selector:
    matchLabels:
      app: flaky-app
      release: 'v{{repl KurlString "Prometheus.Version" }}'
  template:
    metadata:
      labels:
        app: flaky-app
        release: 'v{{repl KurlString "Prometheus.Version" }}'
    spec:
      containers:
        - name: flaky-app
          image: jasoria/flaky-app:latest
          ports:
            - name: http
              containerPort: 3000