apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcatcher
  namespace: monitoring
  labels:
    app: mailcatcher
  annotations:
    kots.io/when: '{{repl ConfigOption "smtp_run_mailcatcher"}}'
spec:
  selector:
    matchLabels:
      app: mailcatcher
  template:
    metadata:
      labels:
        app: mailcatcher
    spec:
      containers:
        - name: mailcatcher
          image: schickling/mailcatcher
          ports:
            - containerPort: 1080
              name: http
            - containerPort: 1025
              name: smtp