apiVersion: v1
kind: Service
metadata:
  name: requestbin
  namespace: monitoring
  labels:
    app: requestbin
  annotations:
    kots.io/when: '{{repl and (IsKurl) (ConfigOption "webhook_run_requestbin") }}'
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 8000
  selector:
    app: requestbin