apiVersion: v1
kind: Service
metadata:
  name: requestbin
  namespace: monitoring
  labels:
    app: requestbin
  annotations:
    kots.io/when: '{{repl and (not IsKurl) (ConfigOption "webhook_run_requestbin") }}'
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: requestbin