apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=flaky-app
        namespace: '{{repl Namespace }}'
    - logs:
        selector:
          - app=requestbin
        namespace: '{{repl Namespace }}'
    - logs:
        selector:
          - app=mailcatcher
        namespace: '{{repl Namespace }}'
    - logs:
        selector:
          - app=comicbox
        namespace: '{{repl Namespace }}'